services:
  db:
    image: postgres:16-alpine
    container_name: ada-db
    environment:
      POSTGRES_DB: ada
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ada"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: dockerfile # (backend, en la raíz)
    container_name: ada-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ada
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  front:
    build:
      context: ./Front
      dockerfile: Dockerfile # (frontend, dentro de Front/)
    container_name: ada-web
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  dbdata:
